apiVersion: v1
kind: Service
metadata:
  annotations:
    supported-by: sre@example.com
  creationTimestamp: null
  labels:
    app: vote
    project: instavote
    tier: front
  name: vote-preview
  namespace: staging
spec:
  ports:
  - name: "80"
    nodePort: 30100
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: vote
  type: NodePort
